### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by NayanKaran** [jahongiry/Portfolio-Desktop-version#3]
### Highlights

✅ Linters are passing
✅ Descriptive pull request
✅ Good commit messages

### Optional Changes 

- [ ] The header section's spacing should match with the Figma template. 

- [ ] The image in the about-me section at the bottom should be placed like a Figma template.

- [ ] The placeholder message should be appropriate.

- [ ] The horizontal line at the "my recent work" heading should match with the Figma template.

**Comment by Paul-js-hub** [comment]
Hello, I like your project. You have used media queries correctly and it's responsive in most screen sizes.

**Comment by Paul-js-hub** [comment]
Hi, please hide the horizontal scroll bar.

**Comment by aeh1707** [comment]
The horizontal scroll is caused by the two scroll bar on the mobile version
